# Generated by Django 3.2.8 on 2021-10-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pic/'),
        ),
    ]
